# Generated by Django 5.1.6 on 2025-03-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
    ]
