# Generated by Django 5.1.6 on 2025-03-25 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_is_pending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chequedeposit',
            name='remarks',
        ),
        migrations.AddField(
            model_name='chequedeposit',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_cheques', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chequedeposit',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chequedeposit',
            name='back_image',
            field=models.ImageField(blank=True, null=True, upload_to='cheque_images/'),
        ),
        migrations.AlterField(
            model_name='chequedeposit',
            name='branch_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chequedeposit',
            name='cheque_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='chequedeposit',
            name='date_of_issue',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chequedeposit',
            name='deposit_account',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chequedeposit',
            name='front_image',
            field=models.ImageField(blank=True, null=True, upload_to='cheque_images/'),
        ),
        migrations.AlterField(
            model_name='chequedeposit',
            name='payee_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chequedeposit',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
