# Generated by Django 5.1.6 on 2025-03-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_investment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='current_value',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
