# Generated by Django 5.1.6 on 2025-03-31 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_investment_account_investment_purchase_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='interest_rate',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='maturity_date',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='reference_number',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='total_cost',
        ),
        migrations.AddField(
            model_name='investment',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='investment',
            name='current_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='investment_type',
            field=models.CharField(choices=[('stock', 'Stocks'), ('bond', 'Bonds'), ('mutual_fund', 'Mutual Funds'), ('etf', 'ETFs'), ('crypto', 'Cryptocurrency')], default='stock', max_length=20),
        ),
        migrations.AlterField(
            model_name='investment',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='investment',
            name='shares',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='investment',
            name='stock_name',
            field=models.CharField(default='Unknown Stock', max_length=100),
        ),
        migrations.AlterField(
            model_name='investment',
            name='symbol',
            field=models.CharField(default='UNKNOWN', max_length=10),
        ),
        migrations.AlterField(
            model_name='investment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('account_type', models.CharField(choices=[('savings', 'Savings'), ('checking', 'Checking'), ('investment', 'Investment')], default='savings', max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='investment',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.account'),
        ),
    ]
