# Generated by Django 5.1.6 on 2025-04-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_userpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='daily_transfer_limit',
            field=models.DecimalField(decimal_places=2, default=5000.0, help_text='Maximum amount the user can transfer in a single day', max_digits=12),
        ),
    ]
